import tkinter
arriba = tkinter.Tk()
arriba.title("Hola Mundo")
arriba.geometry("800x800")
def Accion():
    print("Hola Mundo")
boton = tkinter.Button(arriba, text="Hola Mundo",command=Accion)
#boton.pack()
boton.grid(row=0,column=0)
label = tkinter.Label(arriba, text="Un Label")
#label.pack()
label.grid(row=1,column=1)
check = tkinter.Checkbutton(arriba, text="Un Check")
#check.pack()
entry = tkinter.Entry(arriba)
entry.grid(row=2,column=3)
#entry.pack()
listbox = tkinter.Listbox(arriba)
#listbox.pack()
listbox.grid(column=2,row=3)
message = tkinter.Message(arriba, text="Un Mensaje")
#message.pack()
text = tkinter.Text(arriba)
#text.pack()
radiobutton = tkinter.Radiobutton(arriba, text="Un Radio")
#radiobutton.pack()
arriba.mainloop()

