import tkinter
arriba = tkinter.Tk()
arriba.title("Hola Mundo")
arriba.geometry("800x800")
boton = tkinter.Button(arriba, text="Hola Mundo")
boton.pack()
label = tkinter.Label(arriba, text="Un Label")
label.pack()
check = tkinter.Checkbutton(arriba, text="Un Check")
check.pack()
entry = tkinter.Entry(arriba)
entry.pack()
listbox = tkinter.Listbox(arriba)
listbox.pack()
message = tkinter.Message(arriba, text="Un Mensaje")
message.pack()
text = tkinter.Text(arriba)
text.pack()
radiobutton = tkinter.Radiobutton(arriba, text="Un Radio")
radiobutton.pack()
arriba.mainloop()

